version: '3.3'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - ./.env
    volumes:
    - .:/app
    - /app/node_modules
    command: npm run start:prod
    restart: unless-stopped